### ISSUE TITLE
about checkpoint release

### ISSUE THREAD

**Issue by jiahao-shao1** [minjung-s/BallGAN#2]
Amazing work! 
I am wondering whether it is possible to share your checkpoints. If it is possible, I would really appreciate it!

**Comment by minjung-s** [comment]
Hi, the checkpoint is already shared :)
https://github.com/minjung-s/BallGAN?tab=readme-ov-file#getting-started

**Comment by jiahao-shao1** [comment]
Sorry, I didn't notice it before. Thank you so much!
